### ISSUE TITLE
Video downloads are broken as of today?

### ISSUE THREAD

**Issue by talizea** [y252328/Instagram_Download_Button#21] opened 2022-06-01 00:14 UTC
Looks like instagram changed something.

edit: it appears that instagram reverted something, as it just werks again

**Comment by FlowerForWar** [comment] 2022-06-03 13:16
It seems like the issue is back, as Instagram is having breaking changes.

**Comment by talizea** [comment] 2022-06-03 17:38
Some videos are broken, others work, rather random indeed.

**Comment by y252328** [comment] 2022-06-05 11:35
Thanks for your feedback.
I'm finding the new solution.

**Comment by talizea** [comment] 2022-06-05 16:49
I also noticed that story images are sometimes not downloaded with the best resolution, the first one is from the download button, the second one from I get when using https://github.com/ehmorris/High-Resolution-Downloader-For-Instagram or jDownloader.
![anna__shcherbakova_-20220605_183441-285829876_195559236129778_7109318269505423112_n](https://user-images.githubusercontent.com/21116973/172061216-ca6f950b-ef77-455b-bed2-eb09f4e6df6f.jpeg)
![2022-06-05_anna__shcherbakova_ - CebjPZboO_O](https://user-images.githubusercontent.com/21116973/172061217-7387dec7-81c8-404c-8230-28a97d44fbd3.jpg)

Thank you very much for looking into it! 🫠

**Comment by FlowerForWar** [comment] 2022-06-06 00:07
I'm trying to figure a solution myself, but for some reason I can't figure out, the whole Instagram website is broken for me. Most of the time, a blank page would show up without any contents, unless the DevTools are opened.

**Comment by FlowerForWar** [comment] 2022-06-09 14:39
Any progress on the issue?

**Comment by FlowerForWar** [comment] 2022-06-09 22:41
> I also noticed that story images are sometimes not downloaded with the best resolution, the first one is from the download button, the second one from I get when using https://github.com/ehmorris/High-Resolution-Downloader-For-Instagram or jDownloader. ![anna__shcherbakova_-20220605_183441-285829876_195559236129778_7109318269505423112_n](https://user-images.githubusercontent.com/21116973/172061216-ca6f950b-ef77-455b-bed2-eb09f4e6df6f.jpeg) ![2022-06-05_anna__shcherbakova_ - CebjPZboO_O](https://user-images.githubusercontent.com/21116973/172061217-7387dec7-81c8-404c-8230-28a97d44fbd3.jpg)
> 
> Thank you very much for looking into it! 🫠

Care to share that photo's page in order to test it?

**Comment by talizea** [comment] 2022-06-09 23:21
Just take any instagram story picture, the resolution difference compared to other download methods is consistently different (lower).

Random recent one that should work for the next 24 hours: https://www.instagram.com/stories/eileen_gu_/2857129420782403566/

Download button: 750x1333, 243kb
Other methods: 1170x2080, 488kb

**Comment by FlowerForWar** [comment] 2022-06-10 07:50
This user script tries to get the original image from the `srcset` attribute first, then fallback to to the `src` attribute, if not available. `src` attribute seems to give the original image. Probably, at some point in the past, this wasn't the case. 

Anyways, in the user script code, comment (add // at the start of the line) some lines in `storyGetUrl` function, to match the following
```js
	function storyGetUrl(target, sectionNode) {
		let url = '';
		if (sectionNode.querySelector('video > source')) {
			url = sectionNode.querySelector('video > source').getAttribute('src');
		} else if (sectionNode.querySelector('img[decoding="sync"]')) {
			// let img = sectionNode.querySelector('img[decoding="sync"]');
			// url = img.srcset.split(/ \d+w/g)[0].trim(); // extract first src from srcset attr. of img
			// if (url.length > 0) {
			// 	return url;
			// }
			url = sectionNode.querySelector('img[decoding="sync"]').getAttribute('src');
		}
		return url;
	}
```
And see how the images compared to that extension's images, if they match, then it should be fixed.

**Comment by y252328** [comment] 2022-06-11 12:41
I found that the media id is embedded in the post web page (i.e., https://instagram.com/p/XXX) html head. But I'm not sure if this method works in any environment.
I will release a beta version which uses the info api in the next few days.

**Comment by FlowerForWar** [comment] 2022-06-11 14:43
> 

That solves it then. I don't see why it wouldn't work anywhere.

**Comment by y252328** [comment] 2022-06-11 16:40
I have updated the script which uses the Info API to fetch urls.  
Please update the script and help to test the new method if you can.

**Comment by y252328** [comment] 2022-06-11 17:04
> The update changed nothing for me, some videos can't be downloaded (example: https://www.instagram.com/p/Ceq-PNxgRE5/ ), and story images are still grabbing a lower resolution (example: https://www.instagram.com/stories/anna__shcherbakova_/2858320975204717916/ - 1080x1919 instead of 1284x2282).

I found there is a bug in finding post id.
Could you replace line 397 (let match = link.match...) with `let match = link.match(/^\/p\/([^/]+)\//);` and try again?

Besides, this update(1.13) did not modify the Story part (**maybe** try to fix it in the next update).

**Comment by talizea** [comment] 2022-06-11 18:04
With version 1.13.1 I can download all videos (or at least I tried 5 random ones and it worked every time), great!

**Comment by FlowerForWar** [comment] 2022-06-12 00:15
Great. No issues in here.

**Comment by talizea** [comment] 2022-06-14 12:14
I guess something must have changed, as most video downloads are broken again.

Example: https://www.instagram.com/p/Cex6Kw3FHNd/

**Comment by y252328** [comment] 2022-06-14 13:01
Yes, there are some changes, but fortunately, not big changes.
I have updated the new script to fix it.
Please update and try again.

**Comment by afterdelight** [comment] 2022-07-31 03:48
yeah video download on post and reels dont work for me

**Comment by FlowerForWar** [comment] 2022-08-25 20:05
> yeah video download on post and reels dont work for me

I'm also having the same issue now.

**Comment by afterdelight** [comment] 2022-08-27 15:58
thas cool

**Closed** 2023-01-26 08:01 UTC
